name: Build and Upload Docker Image as Artifact

on:
  push:
    branches: [ "dev", "master" ]
  pull_request:
    branches: [ "dev", "master" ]

env:
  # github.repository as <account>/<repo>
  IMAGE_NAME: cups

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ env.IMAGE_NAME }}:latest --load .

      - name: Save Docker image
        run: |
          docker save ${{ env.IMAGE_NAME }}:latest -o ${{ env.IMAGE_NAME }}.tar

      - name: Upload Docker image to artifacts
        uses: actions/upload-artifact@main
        with:
          name: docker-image
          path: ${{ env.IMAGE_NAME }}.tar
